### ISSUE TITLE
Minted tokens

### ISSUE THREAD

**Issue by luvnft** [michaelshimeles/erc20-token-launchpad#4]
Once tokens are minted how do you find them?

**Comment by michaelshimeles** [comment]
You should see it on the home page, make sure the wallet you connected is the wallet you minted with!

**Comment by luvnft** [comment]
I forked your repo https://basememe.luvnft.com none of the minted coins are displaying.

**Comment by michaelshimeles** [comment]
Did you setup a supabase DB? Check the utils > db folder. There are supabase functions there that store relevant mint information in the DB
